name: mesh23Dtile
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - setuptools
  - pip:
      - pymeshlab==2021.10
      - matplotlib
      - pandas
      - pyproj
      - plyfile
      - trimesh
      - networkx
      - psycopg2-binary
      - pywavefront
      - pyyaml
      - scipy
      - shapely
      - alphashape
      - Pillow
      - laspy
      - psutil
      - lz4
      - pyzmq
      - jsonschema
      - triangle
      - cython